NumPy - Numerical Python

1. Advantages of Numpy Arrays:

2. Allows several Mathematical Operations
Faster operations

In [5]:

import numpy as np
np_array=np.array([1,2,3])

print("For 1 - D , shape gives number of element")
print(np_array)
print(np_array.shape)
print(np_array.ndim)

b = np.array([(1,2,3,4),(5,6,7,8)])
print("For 2 - D , shape gives rows,col")
print(b)
print(b.shape)
print(b.ndim)

For 1 - D , shape gives number of element
[1 2 3]
(3,)
1
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [11]:
#ZEROES,ONES,FULL

x = np.zeros((4,5))
print(x)
x = np.ones((4,5))
print(x)
z = np.full((5,4),5)
print(z)
a = np.eye(5)
print(a)

# create a numpy array with random values
b = np.random.random((3,4))
print(b)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.59653313 0.60550332 0.68536237 0.2141019 ]
 [0.26708282 0.68888397 0.99227959 0.76496833]
 [0.4307847  0.45125292 0.40322542 0.72266609]]


In [13]:
#Linspace to get specific number of elemnts in specific range
d = np.linspace(10,30,5)
print(d)

# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10. 15. 20. 25. 30.]
[10 15 20 25]


In [14]:
#Making Random Array with shape & range being specified
c = np.random.randint(10,90,(5,5))
print(c)
print(c.shape)
print(c.size)
print(c.ndim)

[[86 79 73 56 42]
 [66 16 43 14 26]
 [18 61 86 53 32]
 [86 76 25 26 89]
 [20 26 11 40 21]]
(5, 5)
25
2


In [19]:
array=np.random.randint(10,20,(3,4))
print(array)
print(array.shape)
print("------The Transpose-----")
trans = np.transpose(array)
print(trans)
print(trans.shape)


b = array.reshape(6,2)
print(b)
print(b.shape)


[[18 14 18 18]
 [12 15 12 13]
 [14 10 18 17]]
(3, 4)
------The Transpose-----
[[18 12 14]
 [14 15 10]
 [18 12 18]
 [18 13 17]]
(4, 3)
[[18 14]
 [18 18]
 [12 15]
 [12 13]
 [14 10]
 [18 17]]
(6, 2)


Pandas - Data Processing & framing library , converting & studying data as in form of labelled rows & column
     

In [26]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
iris_dataset = load_iris()


In [28]:
print(iris_dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [27]:
iris_df = pd.DataFrame(iris_dataset.data, columns = iris_dataset.feature_names)

In [29]:
print(iris_df.shape)


(150, 4)


In [30]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [31]:
#For loading some external data
#diabetes_df = pd.read_csv('/content/diabetes.csv')

iris_df.to_csv('iris.csv')

In [34]:
# creating a DatFrame with random values
random_df = pd.DataFrame(np.random.rand(20,10))
print(random_df.head())

          0         1         2         3         4         5         6  \
0  0.531617  0.778544  0.970224  0.559558  0.755752  0.492032  0.561056   
1  0.443211  0.703991  0.471204  0.821102  0.786061  0.553990  0.691483   
2  0.742000  0.989982  0.452411  0.173151  0.289386  0.756247  0.601560   
3  0.867942  0.125448  0.780440  0.629164  0.929317  0.858384  0.415026   
4  0.932602  0.721543  0.661208  0.337191  0.903347  0.000611  0.569645   

          7         8         9  
0  0.415684  0.671108  0.617330  
1  0.034040  0.745494  0.777026  
2  0.092911  0.064002  0.634055  
3  0.712184  0.163300  0.052323  
4  0.731511  0.388528  0.092261  


Basic Details from the DataFrame

In [38]:
print(iris_df.shape)


(150, 4)


In [40]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [41]:
iris_df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [42]:
iris_df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [43]:
iris_df.count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
dtype: int64

In [45]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [46]:
iris_df.std()

sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64

In [48]:
iris_df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [49]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

CORRELATION


Strong positive correlations

Petal length & petal width → 0.962865

Very strong positive correlation

As petal length increases, petal width also increases

Sepal length & petal length → 0.871754

Strong relationship

In [50]:
iris_df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

MATPLOTLIB

SEABORN